'use strict';

module.exports = [
  'appName',
  'testName',
  'browser',
  'url',
  'apiKey',
  'showLogs',
  'saveDebugData',
  'batchName',
  'batchId',
  'properties',
  'baselineBranchName',
  'baselineEnvName',
  'baselineName',
  'envName',
  'ignoreCaret',
  'isDisabled',
  'matchLevel',
  'matchTimeout',
  'parentBranchName',
  'branchName',
  'proxy',
  'saveFailedTests',
  'saveNewTests',
  'compareWithParentBranch',
  'ignoreBaseline',
  'serverUrl',
];
